apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: CONNECTOR_NAME
  labels:
    strimzi.io/cluster: yugabyte-cluster
spec:
  class: io.debezium.connector.yugabytedb.YugabyteDBgRPCConnector
  tasksMax: 1
  config:
    database.hostname: yb-tservers.yb-dev.svc.cluster.local
    database.port: 5433
    database.master.addresses: yb-masters.yb-dev.svc.cluster.local:7100

    snapshot.mode: never

    # Flatten CDC
    transforms: 'unwrap'
    transforms.unwrap.type: 'io.debezium.connector.yugabytedb.transforms.YBExtractNewRecordState'

    # Keep tombstones to propagate delete events downstream
    transforms.unwrap.drop.tombstones: 'false'

    # Remove schema wrapper
    'key.converter.schemas.enable': 'false'

    # Apicurio Avro
    'value.converter': 'io.apicurio.registry.utils.converter.AvroConverter'

    # Source of truth is the database
    'value.converter.apicurio.registry.auto-register': 'true'

    'value.converter.apicurio.registry.use-id': 'contentId'
